### ISSUE TITLE
Publish Images to Docker Hub

### ISSUE THREAD

**Issue by cancan101** [4Catalyzer/docker-dl#20]
Need to create a deploy account and set the appropriate secrets in circle-ci.

``` yaml
deployment:
  hub:
    branch: master
    commands:
      - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
      - ./push-all.sh
```
